#
# Copyright 2017 HyperHQ Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

sudo: required
dist: xenial

os:
  - linux
  - linux-ppc64le

env:
  - target_branch=$TRAVIS_BRANCH

before_script:
  - ".ci/install_go.sh"
  - ".ci/static-checks.sh"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq automake
  - sudo apt-get install -y moreutils

install:
  - cd ${TRAVIS_BUILD_DIR} && make

script:
  - cd ${TRAVIS_BUILD_DIR} && make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
